server:
  port: 8081

spring:
  application:
    name: joke-service

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
  instance:
    instance_id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
