server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://luthier:223666@192.168.136.134:8080/eureka/
  instance:
    instance_id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    # 告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉
    lease-expiration-duration-in-seconds: 2
    # 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 1

spring:
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/shared
        git:
          uri: https://github.com/boyzhangyi/Piano
          search-paths: deploy,deploy/*
          username: boyzhangyi@aliyun.com
          password: z00223666
          default-label: master

from: Piano 1.0.0